### PR TITLE
KDE - lockscreen wallpaper

### PR DESCRIPTION
**Pull request by Mazurel**
Small patch to set KDE lock screen wallpaper if user wants it. Also I have added logger (based on nitrogen) for KDE. It is tested and it works well.

### CODE REVIEW

**Comment by deepjyoti30** [comment]
Hey @Mazurel I think we should rather add a flag that can be passed when calling QuickWall rather than interrupting the user for lockscreen everytime.

Something like ```QuickWall --set-lockscreen```

**Comment by Mazurel** [comment]
Hey, I have tried to make it as you wished, I hope you like it.
It works via `--set-lockscreen` and is disabled by default.

**Comment by deepjyoti30** [comment]
Okay, I will look into it later when I get time. Thanks for the PR

**Comment by deepjyoti30** [comment]
Hey @Mazurel I will check the PR and merge it soon. Was busy this few days.

**Comment by deepjyoti30** [comment]
Hey @Mazurel I checked the code.

If we pass the lockscreen option with some wallpaper setter like nitrogen then I think it will cause an issue because of line 56 in setter.py

```return self.setter(True)``` this line, if called with any  wallpaper setter other than KDE will raise an error. We need to add a check to see if KDE is being selected.

Something like ```if self.lockscreen and self.setter_type == 'kde': # return with True```.

Please make those changes.

**Comment by Mazurel** [comment]
Indeed there was a problem there, I have fixed it by adding variable which stores lockscreen compatible setters. I think that now there shouldn't be any errors.

**Pull request merged**
