### PR TITLE
KDE - restore and tweaks

### PR DESCRIPTION
**Pull request by Mazurel**

### CODE REVIEW

**Comment by deepjyoti30** [comment]
Hey @Mazurel have you tested the changes you made? I can't currently test them because of not using KDE.

**Comment by Mazurel** [comment]
> Hey @Mazurel have you tested the changes you made? I can't currently test them because of not using KDE.

Yes it is tested and it works well on my both kde desktops.

**Comment by deepjyoti30** [comment]
@Mazurel Thanks for the commit then!

**Comment by deepjyoti30** [comment]
Hey @Mazurel , can you confirm if auto detection of wallpaper setter is working on KDE?.
I pushed that in the latest commit.

**Comment by Mazurel** [comment]
> Hey @Mazurel , can you confirm if auto detection of wallpaper setter is working on KDE?.
> I pushed that in the latest commit.

Auto detection works for KDE without any problems.
Great job by the way

**Comment by deepjyoti30** [comment]
Thanks for confirming.

**Pull request merged**
